### ISSUE TITLE
rename the package

### ISSUE THREAD

**Issue by 1st1** [leido/vscode-theme-chromodynamics#2]
Hi,

Would you be able to rename this package to something else?  I'm the original author of this color schema, and I'd like to release an official support for vscode.  Moreover, since we control the MagicPython package, we'd like to have control over adding new features to Chromodynamics to keep the packages in sync.

**Comment by 1st1** [comment]
Hi! Any update on this?

**Comment by rjoomen** [comment]
I love this theme. Could you please yield the name to the original creator, so he can create an officially supported plugin? I'd love to see them develop this further.

**Comment by 1st1** [comment]
Ping?

**Comment by 1st1** [comment]
Ping?

**Comment by leido** [comment]
@1st1 Sry for late response. I've renamed this repo. If you need anything else I'm glad to help.

**Comment by 1st1** [comment]
Hi @leido, thanks a lot for getting back on this!

What we ideally want to happen is to control the chromodynamics name on VSCode Marketplace.  To do that, we have a couple of options:

1. You could add me as a co-owner of the VSCode package. To do that, you can follow these steps: https://github.com/Microsoft/vscode/issues/3670#issuecomment-200277260. If you add me as a co-owner of the package (my email is yselivanov (at) gmail (dot) com), I'll be able to transfer the package myself. The users of the package will not notice anything. This is the preferred option for me.

2. You can rename the package to something else (not mentioning chromodynamics).

3. Of course you can keep things as is and maintain the package yourself. In this case, we'll publish another extension called "Chromodynamics" and there will be two packages sharing almost the same name. This is the least preferable option, as there will be some confusion amongst VSCode users, but, again, it's up to you.

Thanks again!

**Comment by leido** [comment]
Hi @1st1,
 I followed the link you provided but can't find the **publisher page** . Can you help with this?

**Comment by 1st1** [comment]
For me it works the following way (it's way too confusing, btw):

1. Navigate to https://marketplace.visualstudio.com.
2. Click on "Sign In" in the upper-right corner of the page.
3. Sign In with you Microsoft account that you used initially to publish the extension.
4. After a successful sign in, it should navigate you back to https://marketplace.visualstudio.com. If it doesn't, open it again manually.
5. In the upper right-corner you should see a "Publish extensions" link. Click on it.

For me, the last step brings me to the page with a dropdown that https://github.com/Microsoft/vscode/issues/3670#issuecomment-200277260 has a screenshot of.

**Comment by leido** [comment]
Thanks @1st1 
I have added you as a "Owner".
Thanks again for your kindness and patience!

**Comment by 1st1** [comment]
Huge thanks, @leido! I'll follow up on the progress here.

**Comment by rjoomen** [comment]
Any news?

**Comment by 1st1** [comment]
@leido was so kind to give me the full permissions, but I didn't have time to convert things. Will do it soon.
